name: glow-docs
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.7
  - jinja2=3.0.0
  - nptyping=1.3.0
  - numpy>=1.17.4
  - opt_einsum>=3.2.0
  - pandas>=0.25.3
  - pip
  - scikit-learn=0.22.1
  - statsmodels
  - typeguard=2.9.1
  - pip:
      - hail==0.2.58
      - sphinx>=3.0.4
      - sphinx_rtd_theme
      - sphinx-autobuild
      - sphinx-autodoc-typehints
      - sphinx-prompt
      - Sphinx-Substitution-Extensions
      - sphinx-tabs # Code tabs (Python/Scala)
