name: glow-docs
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.10.12
  - jinja2=3.1.2
  - nptyping=2.5.0
  - numpy>=1.23.5
  - opt_einsum>=3.2.0
  - pandas>=1.5.3
  - pip
  - pyyaml
  - scikit-learn=1.1.1
  - statsmodels
  - typeguard=2.13.3
  - pip:
      - sphinx>=3.0.4
      - sphinx_rtd_theme
      - sphinx-autobuild
      - sphinx-autodoc-typehints
      - sphinx-prompt
      - Sphinx-Substitution-Extensions
      - sphinx-tabs # Code tabs (Python/Scala)
